recipe: default.v1

assistant_id: 20240610-121852-immediate-sandcrab

language: es

pipeline:
  - name: SpacyNLP
    model: "es_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_openai_response"
    enable_fallback_prediction: True

logging:
  version: 1
  disable_existing_loggers: False
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: 'DEBUG'
  loggers:
    rasa_sdk:
      handlers: ['console']
      level: 'DEBUG'
      propagate: False
  root:
    handlers: ['console']
    level: 'INFO'
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'